import type {
  ActionGroup,
  ActionGroupListResponse,
  ActionGroupPreview,
  ActionGroupSummary,
  AlertDefinitionCreateInput,
  AlertDefinitionUpdateInput,
  CreateActionGroupInput,
  NotificationSubscription,
  UpdateActionGroupInput,
} from '../src/index';

const createGroup = {
  name: 'Platform operations',
  actions: {
    emails: [{ name: 'Primary', email: 'primary@example.com' }],
    slack: [{ name: 'Operations', webhookUrl: 'https://hooks.slack.com/services/example' }],
    teams: [{ name: 'Cloud team', webhookUrl: 'https://example.webhook.office.com/teams' }],
    webhooks: [
      {
        name: 'Incident intake',
        url: 'https://alerts.example.com/intake',
        auth: { type: 'bearer', tokenRef: 'secret://action-groups/incident-intake' },
      },
    ],
    jira: {
      enabled: true,
      projectKey: 'OPS',
      issueType: 'Incident',
      labels: ['spotto-alert'],
    },
  },
} satisfies CreateActionGroupInput;

const updateGroup = {
  name: 'Platform and security operations',
  actions: createGroup.actions,
} satisfies UpdateActionGroupInput;

const group = {
  id: 'ag-1',
  companyId: 'company-1',
  ...createGroup,
  createdAt: '2026-07-23T00:00:00.000Z',
  createdByUserId: 'user-1',
  updatedAt: '2026-07-23T00:00:00.000Z',
  updatedByUserId: 'user-1',
} satisfies ActionGroup;

const summary = {
  id: group.id,
  companyId: group.companyId,
  name: group.name,
  counts: { emails: 1, slack: 1, teams: 1, webhooks: 1, jira: 1, total: 5 },
  usageCount: 2,
  alertUsageCount: 1,
  notificationUsageCount: 1,
  createdAt: group.createdAt,
  createdByUserId: group.createdByUserId,
  updatedAt: group.updatedAt,
  updatedByUserId: group.updatedByUserId,
} satisfies ActionGroupSummary;

const groupNotification = {
  name: 'Operations events',
  actionGroupId: group.id,
  channel: { type: '' },
  subscriptions: {
    recommendations: [1],
    users: [],
    cloudAccounts: [],
    sharing: [],
  },
} satisfies NotificationSubscription;

const preview = {
  ...summary,
  recipients: {
    emails: [{ name: 'Primary', email: 'primary@example.com' }],
    slack: [{ name: 'Operations' }],
    teams: [{ name: 'Cloud team' }],
    webhooks: [{ name: 'Incident intake' }],
    hasJira: true,
  },
} satisfies ActionGroupPreview;

const invalidPreview = {
  ...preview,
  recipients: {
    ...preview.recipients,
    slack: [
      {
        name: 'Operations',
        // @ts-expect-error Preview records must not expose webhook URLs.
        webhookUrl: 'https://hooks.slack.com/secret',
      },
    ],
  },
} satisfies ActionGroupPreview;

const list = { results: [summary] } satisfies ActionGroupListResponse;

const groupAlert = {
  name: 'Production backup failures',
  enabled: true,
  category: 'other',
  type: 'backupFailure',
  scope: { subscriptionIds: ['sub-1'] },
  criteria: {
    kind: 'backupFailure',
    source: 'dataProtection',
    minimumConsecutiveFailures: 2,
  },
  actionGroupId: group.id,
  notifyOn: ['open', 'resolved'],
} satisfies AlertDefinitionCreateInput;

const updateGroupAlert = {
  name: 'Production backup failures',
  enabled: true,
  scope: { subscriptionIds: ['sub-1'] },
  criteria: { minimumConsecutiveFailures: 3 },
  actionGroupId: group.id,
  notifyOn: ['open'],
} satisfies AlertDefinitionUpdateInput;

const invalidCreateGroup: CreateActionGroupInput = {
  ...createGroup,
  // @ts-expect-error Group IDs are generated by the server.
  id: 'client-id',
};

const invalidUpdateGroup: UpdateActionGroupInput = {
  ...updateGroup,
  // @ts-expect-error A Group cannot be moved to another company.
  companyId: 'company-2',
};

void [
  createGroup,
  updateGroup,
  group,
  summary,
  list,
  preview,
  invalidPreview,
  groupNotification,
  groupAlert,
  updateGroupAlert,
  invalidCreateGroup,
  invalidUpdateGroup,
];
