import type { AlertDefinitionRunState } from '../src/events/alertDefinitionRun';
import type { BaseAlertScope } from '../src/events/baseAlert';
import type { AlertDefinitionCreateInput, AlertDefinitionUpdateInput, QuickAlertCriteria, QuickAlertSummary } from '../src/events/quickAlerts';

const credentialExpiry = {
  kind: 'credentialExpiry',
  source: 'serviceRetirement',
  templateId: 'credential-expiry-30d',
  lookaheadDays: 30,
} satisfies QuickAlertCriteria;

const cloudAccountCredentialExpiry = {
  kind: 'credentialExpiry',
  source: 'cloudAccounts',
  templateId: 'cloud-account-credential-expiry-30d',
  lookaheadDays: 30,
  alertWhenExpiryUnknown: true,
} satisfies QuickAlertCriteria;

const cloudAccountScope = {
  cloudAccountIds: ['account-1'],
} satisfies BaseAlertScope;

const cloudAccountSummary = {
  summaryText: 'Spotto read credential expires soon',
  matchedItemCount: 1,
  source: 'cloudAccounts',
  templateId: 'cloud-account-credential-expiry-30d',
  cloudAccountId: 'account-1',
  cloudAccountName: 'Production Azure',
  credentialRole: 'readServicePrincipal',
  expiryState: 'expiring',
  expiryBasis: 'cloudAccountMetadata',
  expiresAt: '2026-10-01T00:00:00.000Z',
} satisfies QuickAlertSummary;

const cloudAccountRunState = {
  companyId: 'company-1',
  definitionId: 'definition-1',
  lastScopeCloudAccountIdsCount: 1,
  lastScopeCloudAccountIdsSample: ['account-1'],
  lastSourceCoverageStatus: 'partial',
  lastSourceFailedItemCount: 1,
} satisfies AlertDefinitionRunState;

const cloudAccountDefinition = {
  name: 'Cloud Account credential expires soon',
  enabled: true,
  category: 'other',
  type: 'credentialExpiry',
  scope: cloudAccountScope,
  criteria: cloudAccountCredentialExpiry,
} satisfies AlertDefinitionCreateInput;

const cloudAccountDefinitionUpdate = {
  name: 'Cloud Account credential expiry',
  enabled: true,
  scope: cloudAccountScope,
  criteria: {
    lookaheadDays: 14,
    alertWhenExpiryUnknown: false,
  },
} satisfies AlertDefinitionUpdateInput;

const benefitExpiry = {
  kind: 'benefitExpiry',
  source: 'commitmentsPlanning',
  templateId: 'benefit-expiry-30d',
  lookaheadDays: 30,
  benefitTypes: ['reservation', 'savingsPlan'],
} satisfies QuickAlertCriteria;

const serviceRetirement = {
  kind: 'serviceRetirement',
  source: 'serviceRetirement',
  templateId: 'service-retirement-30d',
  lookaheadDays: 90,
} satisfies QuickAlertCriteria;

const backupFailure = {
  kind: 'backupFailure',
  source: 'dataProtection',
  templateId: 'backup-failure',
  minimumConsecutiveFailures: 2,
  workloadTypes: ['AzureIaasVM', 'AzureFiles'],
} satisfies QuickAlertCriteria;

const createDefinition = {
  name: 'Backup failures detected',
  enabled: true,
  category: 'other',
  type: 'backupFailure',
  scope: { subscriptionIds: ['sub-1'] },
  criteria: backupFailure,
  destinations: { emails: [{ email: 'alerts@example.com' }] },
} satisfies AlertDefinitionCreateInput;

const updateDefinition = {
  name: 'Backup failures detected twice',
  enabled: true,
  scope: { subscriptionIds: ['sub-1'] },
  criteria: {
    minimumConsecutiveFailures: 2,
    workloadTypes: ['AzureIaasVM'],
  },
  destinations: { emails: [{ email: 'alerts@example.com' }] },
} satisfies AlertDefinitionUpdateInput;

const invalidCreateDefinition: AlertDefinitionCreateInput = {
  ...createDefinition,
  // @ts-expect-error Definition IDs are generated by the server.
  id: 'client-id',
};

const invalidUpdateDefinition: AlertDefinitionUpdateInput = {
  ...updateDefinition,
  // @ts-expect-error Alert type is immutable after creation.
  type: 'credentialExpiry',
};

const invalidUpdateCriteria: AlertDefinitionUpdateInput = {
  ...updateDefinition,
  criteria: {
    ...updateDefinition.criteria,
    // @ts-expect-error Alert source is immutable after creation.
    source: 'dataProtection',
  },
};

const invalidBackupRule: QuickAlertCriteria = {
  kind: 'backupFailure',
  source: 'dataProtection',
  templateId: 'backup-failure',
  // @ts-expect-error Backup failure criteria do not use an expiry window.
  lookaheadDays: 30,
};

const invalidBenefitRule: QuickAlertCriteria = {
  kind: 'benefitExpiry',
  source: 'commitmentsPlanning',
  templateId: 'benefit-expiry-7d',
  lookaheadDays: 7,
  // @ts-expect-error Benefit expiry criteria do not use consecutive failures.
  minimumConsecutiveFailures: 2,
};

void [
  credentialExpiry,
  cloudAccountCredentialExpiry,
  cloudAccountScope,
  cloudAccountSummary,
  cloudAccountRunState,
  cloudAccountDefinition,
  cloudAccountDefinitionUpdate,
  benefitExpiry,
  serviceRetirement,
  backupFailure,
  createDefinition,
  updateDefinition,
  invalidCreateDefinition,
  invalidUpdateDefinition,
  invalidUpdateCriteria,
  invalidBackupRule,
  invalidBenefitRule,
];
